#!/bin/bash
read -p"Enter project name:" appName
read -p"Enter project Directory:" directory
mkdir  $directory/$appName
cd $directory/$appName
touch index.html app.js style.css
echo "
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel=\"stylesheet\" href=\"style.css\">
    <title>Document</title>
</head>
<body>
    <h1>Hello, World</h1>
    <script src=\"./app.js\"></script>
</body>
</html>" > index.html

echo "console.log(\"Hello, World\")" > app.js
